### ISSUE TITLE
Single element sequence is not preserved in coversion in Get-Yaml

### ISSUE THREAD

**Issue by rickjury** [scottmuc/PowerYaml#12]
I have found a problem. If a Yaml contains a sequence with only 1 child node that is a mapping, get-yaml returns an object in which the sequence does not turn into an array, instead it just becomes 1 level shallower in the tree. i.e. 

```
mapping:
   -
       mapping:
               a: b
               c:  d

turns into

mapping:
       mapping:
               a: b
               c:  d
```

I've only seen this happen with a single element sequence. 

I noticed this as I'm trying to use to script up configuration of yaml files for datadog agents. Most datadog yaml files have an "instances" sequence that contains 1.n instances each of which is a mapping table. Often there is only a [0] in it.

e.g if I import this with get-yaml.

```

---

   init_config: '' 
   instances: 
      -  
         interpreter: 'C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe' 
         params: 
            - '-collectList "Web Service1,Web Service3"' 
            - '-send 1' 
         min_collection_interval: '60' 
         skip_event: 'True' 
         name: 'PowershellTest' 
         script: 'C:\ProgramData\something\ascript.ps1'

it ends up as an object that with the single level sequence vanishing out of the tree. as yaml this ends up as:

---

     init_config: '' 
     instances: 
         interpreter: 'C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe' 
         params: 
            - '-collectList "Web Service1,Web Service3"' 
            - '-send 1' 
         min_collection_interval: '60' 
         skip_event: 'True' 
         name: 'PowershellTest' 
         script: 'C:\ProgramData\something\ascript.ps1'
```

The problem occurs as Get-Yaml is parsing Get-YamlDocument -File ... somewhere. The yaml object returned by Get-YamlDocument still has the since element sequence in it.
![nodash](https://cloud.githubusercontent.com/assets/11447143/10921560/29e659a6-82db-11e5-9272-84cb0fabfc98.png)
![yamlobjectwith-](https://cloud.githubusercontent.com/assets/11447143/10921561/29e67ec2-82db-11e5-8ebb-72f953c830d1.PNG)
