### ISSUE TITLE
Expand Ansible variables

### ISSUE THREAD

**Issue by dracorp** [scottmuc/PowerYaml#14]
Hi
Could you add a functionality to read and expand Ansible variables and even nested variables?

```
directory:
  main: foo
  temp: "{{ main }}\tmp"
  archive: "{{ main/temp }}\archive"
```

```
PS C:\dev> $yaml = Get-Yaml -FromFile (Resolve-Path .\sample.yml)
PS C:\dev> $yaml.directory.temp
foo\tmp
PS C:\dev> $yaml.directory.archive
foo\tmp\archive
# or
PS C:\dev> $yaml.getData ('directory', 'archive')
foo\tmp\archive
```

Or I should write to YAML.net's author?

Links:
- https://docs.ansible.com/ansible/YAMLSyntax.html#gotchas
