### ISSUE TITLE
effectively work with merge keys

### ISSUE THREAD

**Issue by rismoney** [scottmuc/PowerYaml#5]
How do you recommend approaching merge keys?

Say I have the following yaml file:

```
defaults: &defaults
  subnetmask: 255.255.255.0
SERVER1:
  NIC1:
    ipaddress: 1.2.3.4
    <<: *defaults
```

$nicyaml.server1.nic1 contains a name "<<"
It then correctly enumerates the merge like:
$nicyaml.server1.nic1."<<".subnetmask

Then to work with it though, do I need to check if a merge key exists and then iterate $nicyaml.server1.nic1."<<".keys ?   i wonder if this logic should be built into the module vs. in my script...  Ideally I think it would be $nicyaml.server1.nic1.subnetmask since the module would interpret the merge since you are dumping it into objects, unless there is a need to preserve...

thoughts?
